workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "dev"
          include: true
      cancel_previous_builds: false
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.solo.flutterCodemagicApp
    integrations:
      app_store_connect: SolomonAPIKey
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          # Get current store version (1.0.3)
          STORE_VERSION=$(app-store-connect get-latest-app-store-version "$APP_STORE_ID || echo "1.0.0")
          echo "Current Store Version: $STORE_VERSION"

          # Calculate new version (1.0.4)
          MAJOR=$(echo $STORE_VERSION | cut -d. -f1)
          MINOR=$(echo $STORE_VERSION | cut -d. -f2)
          PATCH=$(echo $STORE_VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          # Get and increment build number
          CURRENT_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID")
          NEW_BUILD=$((CURRENT_BUILD + 1))
          # Update pubspec.yaml
          sed -i '' "s/version: .*/version: $NEW_VERSION+$NEW_BUILD/" pubspec.yaml

          echo "Building $NEW_VERSION+$NEW_BUILD (Current Store: $STORE_VERSION+$CURRENT_BUILD)"
          flutter build ipa --release \
            --build-name="$VERSION_NAME" \
            --build-number="$NEW_BUILD" \
            --export-options-plist="/Users/builder/export_options.plist"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
# workflows:
#   android-workflow:
#     name: Android Sample Workflow
#     instance_type: mac_mini_m2
#     max_build_duration: 120
#     environment:
#       flutter: stable
#       android_signing:
#         - cm_keystore_credentials
#       groups:
#         - google_credentials
#     scripts:
#       - name: Set up local.properties
#         script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
#       - name: Install Flutter dependencies
#         script: flutter pub get
#       - name: Build AAB with Flutter
#         script:
#           CURRENT_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "com.solo.flutter_codemagic_app" --tracks="internal")
#           echo "versionCode=$((CURRENT_BUILD_NUMBER + 1))" > "$CM_BUILD_DIR/version.properties"
#           flutter build appbundle --release --build-number=$(($CURRENT_BUILD_NUMBER + 1))

#     artifacts:
#       - build/**/outputs/**/*.aab
#       - build/**/outputs/**/mapping.txt
#       - flutter_drive.log
#     publishing:
#       email:
#         recipients:
#           - solomon@codemagic.io
#       google_play:
#         track: internal
#         credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
#         submit_as_draft: true
