workflows:
  android-workflow:
    name: Android Sample Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      android_signing:
        - cm_keystore_credentials
      groups:
        - google_credentials
    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build AAB with Flutter
        script: flutter build appbundle --release

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - solomon@codemagic.io
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
