workflows:
  android-workflow:
    name: Android Sample Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      android_signing:
        - cm_keystore_credentials
      groups:
        - google_credentials
        - shorebird_credentials
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx5g"
    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK debug
        script: |
          flutter build apk --debug
      - name: Build AAB with Flutter
        script:
          CURRENT_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "com.solo.flutter_codemagic_app" --tracks="internal")
          echo "versionCode=$((CURRENT_BUILD_NUMBER + 1))" > "$CM_BUILD_DIR/version.properties"
          flutter build appbundle --release --build-number=$(($CURRENT_BUILD_NUMBER + 1))
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - solteqinnovationsltd@gmail.com
      scripts:
        - name: Build finished successfully
          script: touch ~/SUCCESS
        - name: Report build status
          script: |
            if [ -f ~/SUCCESS ]; then
              echo "Final build status: $CM_BUILD_STATUS"
              if [ "$CM_BUILD_STATUS" = "success" ]; then
                curl -X POST https://api.codemagic.io/hooks/67f8f1f04701b071a6f29f3a \
                  -H "Content-Type: application/json" \
                  -d '{
                    "message": "✅ Build succeeded!",
                    "build_number": "'"$CM_BUILD_NUMBER"'",
                    "status": "success"
                  }'
              else
                curl -X POST https://api.codemagic.io/hooks/67f8f1f04701b071a6f29f3a \
                  -H "Content-Type: application/json" \
                  -d '{
                    "message": "❌ Build failed!",
                    "build_number": "'"$CM_BUILD_NUMBER"'",
                    "status": "failed",
                    "error": "'"$CM_BUILD_STATUS_MESSAGE"'"
                  }'
              fi
            else
              echo "Build failed before reaching publishing stage"
            fi

workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "dev"
          include: true
      cancel_previous_builds: false
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        # - shorebird_credentials
        - appstore_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ${BUNDLE_ID}
    integrations:
      app_store_connect: SolomonAPIKey
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods
        script: find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist="/Users/builder/export_options.plist" \
            --build-name=$(grep "version:" pubspec.yaml | head -n 1 | awk '{print $2}' | cut -d'+' -f1) \
            --build-number=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    # artifacts:
    #   - build/ios/iphonesimulator/Runner.app
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
        release_type: AFTER_APPROVAL