workflows:
  android-workflow:
    name: Android Sample Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      android_signing:
        - cm_keystore_credentials
      groups:
        - google_credentials
    scripts:
      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build AAB with Flutter
        script:
          CURRENT_BUILD_VERSION=$(google-play get-latest-build-number --package-name "com.solo.flutter_codemagic_app" --tracks="internal")
          echo "versionCode=$((CURRENT_BUILD_VERSION + 1))" > "$CM_BUILD_DIR/version.properties"
          flutter build appbundle --release --build-number=$(($CURRENT_BUILD_VERSION + 1))

    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - solomon@codemagic.io
      google_play:
        track: internal
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        submit_as_draft: true
